source 'https://rubygems.org'


gem 'rails'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass', '~> 4.5.0'
gem "loofah", ">= 2.2.3"

group :development do
  gem 'spring'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara', "~> 2.5"
  gem 'launchy'
  gem 'pry'
end
